### ISSUE TITLE
Compiler segfault with `in`

### ISSUE THREAD

**Issue by hstormo** [odin-lang/Odin#1317]
## Context

* Operating System: `Linux 5.4.0-90-generic x86_64`
* Please paste `odin version` output: `dev-2021-11:acd5878d`

Code:
```
package main

foo :: proc() {}
main :: proc() {
    x in foo()
}
```

Backtrace:
```
Thread 1 "odin" received signal SIGSEGV, Segmentation fault.
0x00000000004836bd in is_type_bit_set (t=0x0) at src/types.cpp:1616
1616		return (t->kind == Type_BitSet);
(gdb) bt
#0  0x00000000004836bd in is_type_bit_set (t=0x0) at src/types.cpp:1616
#1  0x00000000004b7d7c in check_binary_expr (c=0x7fffffffc850, x=0x7fffffffbf80, node=0x7ffff01e1730, type_hint=0x0, use_lhs_as_type_hint=true) at src/check_expr.cpp:2913
#2  0x00000000004f26c1 in check_expr_base_internal (c=0x7fffffffc850, o=0x7fffffffbf80, node=0x7ffff01e1730, type_hint=0x0) at src/check_expr.cpp:8316
#3  0x00000000004bffc0 in check_expr_base (c=0x7fffffffc850, o=0x7fffffffbf80, node=0x7ffff01e1730, type_hint=0x0) at src/check_expr.cpp:8891
#4  0x000000000051312e in check_stmt_internal (ctx=0x7fffffffc850, node=0x7ffff01e17a0, flags=32) at src/check_stmt.cpp:1471
#5  0x0000000000511bf9 in check_stmt (ctx=0x7fffffffc850, node=0x7ffff01e17a0, flags=32) at src/check_stmt.cpp:496
#6  0x0000000000510804 in check_stmt_list (ctx=0x7fffffffc850, stmts=..., flags=32) at src/check_stmt.cpp:102
#7  0x000000000051002a in check_proc_body (ctx_=0x7fffffffca50, token=..., decl=0x7fffe58b9920, type=0x7ffff26c6460, body=0x7ffff01e17e0) at src/check_decl.cpp:1352
#8  0x0000000000528aa4 in check_proc_info (c=0x7ffff220a7c0, pi=0x7ffff26c6b30, untyped=0x7fffffffcd60, procs_to_check_queue=0x7ffff220b1c8) at src/checker.cpp:4779
#9  0x00000000005293d3 in consume_proc_info_queue (c=0x7ffff220a7c0, pi=0x7ffff26c6b30, q=0x7ffff220b1c8, untyped=0x7fffffffcd60) at src/checker.cpp:4890
#10 0x0000000000529ef4 in check_procedure_bodies (c=0x7ffff220a7c0) at src/checker.cpp:4939
#11 0x000000000052cbb2 in check_parsed_files (c=0x7ffff220a7c0) at src/checker.cpp:5322
#12 0x00000000005e62b0 in main (arg_count=3, arg_ptr=0x7fffffffdef8) at src/main.cpp:2603
(gdb)
```

**Comment by gingerBill** [comment]
Cannot replicate any more.
