### ISSUE TITLE
Runtime crash when returning `bit_set` as part of aggregate types

### ISSUE THREAD

**Issue by ap29600** [odin-lang/Odin#1319]
## Context

* Operating System & Odin Version:
    * Odin: dev-2021-11:be1811d3 (built against llvm 13.0.0-3)
    * OS:   Arch Linux, Linux 5.15.2-arch1-1
    * CPU:  AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx

## Expected Behavior
value of type `Maybe(bitset[0..64])` is constructed

## Current Behavior
program crashes with invalid memory access to address `0x8`

## Failure Information (for bugs)
only seems to happen when the `bit_set` is part of aggregate types such as struct or union, or in the case of multiple return values.
Additionally, providing the underlying type to the bitset, as in `bit_set[0..64; u128]` avoids the crash, as does using a `bit_set` that ends up fitting in a `u64`.

curiously, the generated llvm code for omitted or specified underlying data type is identical:

```go
foo :: proc () -> Maybe(bit_set[0..64]) {
  return bit_set[0..64]{}
}

bar :: proc () -> Maybe(bit_set[0..64; u128]) {
  return bit_set[0..64; u128]{}
}


```

```llvm
define dllexport void @foo(%"fail.Maybe(bit_set[0 .. 64])-2515"* noalias sret(%"fail.Maybe(bit_set[0 .. 64])-2515") %agg.result, i8* noalias nocapture nonnull %__.context_ptr) !dbg !696 {
decls:
  %0 = alloca %"fail.Maybe(bit_set[0 .. 64])-2515", align 16, !dbg !772
  br label %entry, !dbg !774

entry:                                            ; preds = %decls
  call void @llvm.dbg.declare(metadata %runtime.Context* undef, metadata !771, metadata !DIExpression()), !dbg !774
  %1 = bitcast %"fail.Maybe(bit_set[0 .. 64])-2515"* %0 to i8*, !dbg !772
  call void @llvm.memset.p0i8.i64(i8* %1, i8 0, i64 32, i1 false), !dbg !772
  %2 = bitcast %"fail.Maybe(bit_set[0 .. 64])-2515"* %0 to i128*, !dbg !772
  store i128 0, i128* %2, align 8, !dbg !772
  %3 = getelementptr inbounds %"fail.Maybe(bit_set[0 .. 64])-2515", %"fail.Maybe(bit_set[0 .. 64])-2515"* %0, i32 0, i32 1, !dbg !772
  store i64 1, i64* %3, align 8, !dbg !772
  %4 = load %"fail.Maybe(bit_set[0 .. 64])-2515", %"fail.Maybe(bit_set[0 .. 64])-2515"* %0, align 8, !dbg !772
  store %"fail.Maybe(bit_set[0 .. 64])-2515" %4, %"fail.Maybe(bit_set[0 .. 64])-2515"* %agg.result, align 8, !dbg !772
  ret void, !dbg !772
}

define dllexport void @bar(%"fail.Maybe(bit_set[0 .. 64])-2541"* noalias sret(%"fail.Maybe(bit_set[0 .. 64])-2541") %agg.result, i8* noalias nocapture nonnull %__.context_ptr) !dbg !775 {
decls:
  %0 = alloca %"fail.Maybe(bit_set[0 .. 64])-2541", align 8, !dbg !850
  br label %entry, !dbg !852

entry:                                            ; preds = %decls
  call void @llvm.dbg.declare(metadata %runtime.Context* undef, metadata !849, metadata !DIExpression()), !dbg !852
  %1 = bitcast %"fail.Maybe(bit_set[0 .. 64])-2541"* %0 to i8*, !dbg !850
  call void @llvm.memset.p0i8.i64(i8* %1, i8 0, i64 24, i1 false), !dbg !850
  %2 = bitcast %"fail.Maybe(bit_set[0 .. 64])-2541"* %0 to i128*, !dbg !850
  store i128 0, i128* %2, align 8, !dbg !850
  %3 = getelementptr inbounds %"fail.Maybe(bit_set[0 .. 64])-2541", %"fail.Maybe(bit_set[0 .. 64])-2541"* %0, i32 0, i32 1, !dbg !850
  store i64 1, i64* %3, align 8, !dbg !850
  %4 = load %"fail.Maybe(bit_set[0 .. 64])-2541", %"fail.Maybe(bit_set[0 .. 64])-2541"* %0, align 8, !dbg !850
  store %"fail.Maybe(bit_set[0 .. 64])-2541" %4, %"fail.Maybe(bit_set[0 .. 64])-2541"* %agg.result, align 8, !dbg !850
  ret void, !dbg !850
}
```

what is different is the code for `main` (namely the arguments to memset):

for the version with `bit_set[0..64]`:
```llvm
...
  %2 = bitcast i8* %__.context_ptr to %runtime.Context*
  %3 = bitcast %"fail.Maybe(bit_set[0 .. 64])-2515"* %0 to i8*, !dbg !860
  call void @llvm.memset.p0i8.i64(i8* %3, i8 0, i64 32, i1 false), !dbg !860
  %4 = bitcast %"fail.Maybe(bit_set[0 .. 64])-2515"* %1 to i8*, !dbg !860
  call void @llvm.memset.p0i8.i64(i8* %4, i8 0, i64 32, i1 false), !dbg !860
  %5 = bitcast %runtime.Context* %2 to i8*, !dbg !860
...
```

for the version with `bit_set[0..64; u128]`:
```llvm
...
  %2 = bitcast i8* %__.context_ptr to %runtime.Context*
  %3 = bitcast %"fail.Maybe(bit_set[0 .. 64])-2783"* %0 to i8*, !dbg !860
  call void @llvm.memset.p0i8.i64(i8* %3, i8 0, i64 24, i1 false), !dbg !860
  %4 = bitcast %"fail.Maybe(bit_set[0 .. 64])-2783"* %1 to i8*, !dbg !860
  call void @llvm.memset.p0i8.i64(i8* %4, i8 0, i64 24, i1 false), !dbg !860
  %5 = bitcast %runtime.Context* %2 to i8*, !dbg !860
...
```

### Steps to Reproduce

compile and run the following code:

```go
package fail

foo :: proc () -> Maybe(bit_set[0..64]) {
  return bit_set[0..64]{}
}

main :: proc () {
  result := foo()
}
```

### Failure Logs
unfortunately backtrace looks like this, for some reason I don't get stack frame names in gdb for Odin.
```
0x0000000000407a75 in main ()
(gdb)
Single stepping until exit from function main,
which has no line number information.
fail.main () at fail.odin:11
11      main :: proc () {
(gdb)
12        result := foo()
(gdb)
fail.foo-450 () at fail.odin:3
3       foo :: proc () -> Maybe(bit_set[0..64]) {
(gdb)
4         return bit_set[0..64]{}
(gdb)
Warning:
Cannot insert breakpoint 0.
Cannot access memory at address 0x8

0x0000000000000000 in ?? ()

(gdb) backtrace
#0  0x0000000000000000 in ?? ()
#1  0x0000000000000008 in ?? ()
#2  0x00007fffffffe638 in ?? ()
#3  0x0000000000000000 in ?? ()
```
but failure seems to occur in `fail.main` or immediately before returning to it.

**Comment by gingerBill** [comment]
I know what is causing this. Looks like a simple fix.
