### ISSUE TITLE
crash when passing constant parapoly procedure to parapoly

### ISSUE THREAD

**Issue by graphitemaster** [odin-lang/Odin#1822]
Trivial case provided below
```odin
test :: proc($c: $C) {}
main :: proc() { test(proc(){}); }
```

Backtrace provided here, it looks like a null pointer dereference off something exposing an atomic at `0x58` bytes from that pointer
```
0x0000555555775ce3 in std::__atomic_base<Ast*>::load (this=0x58, __m=std::memory_order_seq_cst) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/bits/atomic_base.h:838
838     /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/bits/atomic_base.h: No such file or directory.
(gdb) bt
#0  0x0000555555775ce3 in std::__atomic_base<Ast*>::load (this=0x58, __m=std::memory_order_seq_cst)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/bits/atomic_base.h:838
#1  std::atomic<Ast*>::load (this=0x58, __m=std::memory_order_seq_cst)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/atomic:570
#2  0x0000555555667512 in check_get_params (ctx=0x7fffffff9188, scope=0x7fff498816a0, _params=0x7fff867fb370, is_variadic_=0x7fffffff9187, 
    variadic_index_=0x7fffffff9178, success_=0x7fffffff9177, specialization_count_=0x7fffffff9168, operands=0x7fffffff9740) at src/check_type.cpp:1646
#3  0x0000555555609c68 in check_procedure_type (ctx=0x7fffffff95d0, type=0x7fff49881770, proc_type_node=0x7fff867fb3e0, operands=0x7fffffff9740)
    at src/check_type.cpp:1963
```

**Comment by Kelimion** [comment]
Fixed, now returns "Expected a constant value for this polymorphic name parameter".
