### ISSUE TITLE
Segfault during type checking

### ISSUE THREAD

**Issue by zen3ger** [odin-lang/Odin#3953]
## Context

When compiling the following code the compiler segfaults in `is_type_map`:
```
package repro
foo :: proc() {}
main :: proc() { for i in foo() {} }
```

* Operating System & Odin Version:
```
Useful information to add to a bug report:

	Odin:    dev-2024-07:fc5ce30f3
	OS:      openSUSE Tumbleweed, Linux 6.9.7-1-default
	CPU:     AMD Ryzen 9 5900X 12-Core Processor            
	RAM:     32001 MiB
	Backend: LLVM 18.1.8
```

## Expected Behavior

Compile error with type mismatch pointing to the return type (void) of `foo`.

## Current Behavior

Segfault in `is_type_map`.

## Failure Information (for bugs)

```
Thread 9 "odin" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeb2006c0 (LWP 45647)]
0x000055555566f5cd in is_type_map (t=0x0) at src/types.cpp:1797
1797		return t->kind == Type_Map;
(gdb) bt
#0  0x000055555566f5cd in is_type_map (t=0x0) at src/types.cpp:1797
#1  0x0000555555666759 in check_range_stmt (ctx=0x7fffeb1ff7a0, node=0x7fffe00330b0, mod_flags=32) at src/check_stmt.cpp:1840
#2  0x0000555555660791 in check_stmt_internal (ctx=0x7fffeb1ff7a0, node=0x7fffe00330b0, flags=32) at src/check_stmt.cpp:2615
#3  0x000055555565fc35 in check_stmt (ctx=0x7fffeb1ff7a0, node=0x7fffe00330b0, flags=32) at src/check_stmt.cpp:662
#4  0x000055555565da1d in check_stmt_list (ctx=0x7fffeb1ff7a0, stmts=..., flags=32) at src/check_stmt.cpp:108
#5  0x000055555565bd7f in check_proc_body (ctx_=0x7fffeb1ff9e0, token=..., decl=0x7fffc840c0e0, type=0x7fffe01bfdd0, body=0x7fffe00331d0) at src/check_decl.cpp:1827
#6  0x000055555565adb3 in check_proc_info (c=0x7fffe00306d0, pi=0x7fffe01bfee0, untyped=0x7fffe00b3448) at src/checker.cpp:5794
#7  0x000055555565a690 in check_proc_info_worker_proc (data=0x7fffe01bfee0) at src/checker.cpp:5970
#8  0x00005555555c8c08 in thread_pool_thread_proc (thread=0x7fffefa01650) at src/thread_pool.cpp:218
#9  0x00005555555c870f in internal_thread_proc (arg=0x7fffefa01650) at src/threading.cpp:561
#10 0x00007ffff0492ba2 in start_thread () from /lib64/libc.so.6
#11 0x00007ffff051400c in clone3 () from /lib64/libc.so.6
```
### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. build the provided program under `Context`
2. segfault

**Comment by Kelimion** [comment]
Good find, thanks. Fixed.
