### ISSUE TITLE
Segfault in is_divigering_stmt

### ISSUE THREAD

**Issue by nakst** [odin-lang/Odin#864]
## Context

ArchLinux 64-bit with Odin commit 8784b79.

## Expected Behavior

I expect running `./odin build test.odin` where `test.odin` contains the following:

```odin
package test

main :: proc() {
    if a.a() {
    } else {
        a.b("\n");
        a.b(1);
    }
}

```

to not crash.

## Current Behavior

It crashes.

## Failure Information (for bugs)

Before the crash, the following is printed by the Odin compiler:
```
test.odin(4:8) Undeclared name: a
test.odin(6:9) Undeclared name: a
```

It crashes in `check_stmt.cpp:15`, in `is_divigering_stmt`, trying to dereference a null pointer, `t`. A backtrace provided by the GDB is included.

```
Thread 1 "odin" received signal SIGSEGV, Segmentation fault.
0x0000000000502aa3 in is_divigering_stmt (stmt=0x7fffe004a490) at src/check_stmt.cpp:15
15		return t->kind == Type_Proc && t->Proc.diverging;
(gdb) p t
$1 = (Type *) 0x0
(gdb) bt
#0  0x0000000000502aa3 in is_divigering_stmt (stmt=0x7fffe004a490) at src/check_stmt.cpp:15
#1  0x0000000000501ca6 in check_stmt_list (ctx=0x7fffffffb988, stmts=..., flags=32)
    at src/check_stmt.cpp:72
#2  0x0000000000505cd9 in check_stmt_internal (ctx=0x7fffffffb988, node=0x7fffe004a7e0, flags=32)
    at src/check_stmt.cpp:1539
#3  0x0000000000502b89 in check_stmt (ctx=0x7fffffffb988, node=0x7fffe004a7e0, flags=32)
    at src/check_stmt.cpp:421
#4  0x0000000000505f13 in check_stmt_internal (ctx=0x7fffffffb988, node=0x7fffe004a890, flags=32)
    at src/check_stmt.cpp:1565
#5  0x0000000000502b89 in check_stmt (ctx=0x7fffffffb988, node=0x7fffe004a890, flags=32)
    at src/check_stmt.cpp:421
#6  0x0000000000501c08 in check_stmt_list (ctx=0x7fffffffb988, stmts=..., flags=32)
    at src/check_stmt.cpp:59
#7  0x000000000050169a in check_proc_body (ctx_=0x7fffffffbbe0, token=..., decl=0x7ffff61b5c70, 
    type=0x7ffff630d5b0, body=0x7fffe004a920) at src/check_decl.cpp:1253
#8  0x00000000005190d1 in check_proc_info (c=0x7fffffffd820, pi=...) at src/checker.cpp:4373
#9  0x0000000000519d94 in check_parsed_files (c=0x7fffffffd820) at src/checker.cpp:4482
#10 0x000000000059e49f in main (arg_count=3, arg_ptr=0x7fffffffe8e8) at src/main.cpp:2068
(gdb) 
```

Before the crash occurs, the following invalid reads are noted by Valgrind.

```
==10369== Invalid read of size 8
==10369==    at 0x49834B: add_entity_with_name(Checker*, Scope*, Ast*, Entity*, String) (checker.cpp:1175)
==10369==    by 0x4983D8: add_entity(Checker*, Scope*, Ast*, Entity*) (checker.cpp:1182)
==10369==    by 0x4F1508: check_get_params(CheckerContext*, Scope*, Ast*, bool*, long*, bool*, long*, Array<Operand>*) (check_type.cpp:1748)
==10369==    by 0x4A24BF: check_procedure_type(CheckerContext*, Type*, Ast*, Array<Operand>*) (check_type.cpp:2533)
==10369==    by 0x4FE187: check_proc_decl(CheckerContext*, Entity*, DeclInfo*) (check_decl.cpp:661)
==10369==    by 0x49CDEE: check_entity_decl(CheckerContext*, Entity*, DeclInfo*, Type*) (check_decl.cpp:1129)
==10369==    by 0x49C6FD: check_single_global_entity(Checker*, Entity*, DeclInfo*) (checker.cpp:3427)
==10369==    by 0x513260: check_all_global_entities(Checker*) (checker.cpp:3436)
==10369==    by 0x519B0C: check_parsed_files(Checker*) (checker.cpp:4469)
==10369==    by 0x59E49E: main (main.cpp:2068)
==10369==  Address 0x1ffeff5318 is on thread 1's stack
==10369==  29688 bytes below stack pointer
==10369== 
==10369== Invalid read of size 8
==10369==    at 0x49834B: add_entity_with_name(Checker*, Scope*, Ast*, Entity*, String) (checker.cpp:1175)
==10369==    by 0x4983D8: add_entity(Checker*, Scope*, Ast*, Entity*) (checker.cpp:1182)
==10369==    by 0x4F22E8: check_get_results(CheckerContext*, Scope*, Ast*) (check_type.cpp:1875)
==10369==    by 0x4A24E5: check_procedure_type(CheckerContext*, Type*, Ast*, Array<Operand>*) (check_type.cpp:2534)
==10369==    by 0x4FE187: check_proc_decl(CheckerContext*, Entity*, DeclInfo*) (check_decl.cpp:661)
==10369==    by 0x49CDEE: check_entity_decl(CheckerContext*, Entity*, DeclInfo*, Type*) (check_decl.cpp:1129)
==10369==    by 0x49C6FD: check_single_global_entity(Checker*, Entity*, DeclInfo*) (checker.cpp:3427)
==10369==    by 0x513260: check_all_global_entities(Checker*) (checker.cpp:3436)
==10369==    by 0x519B0C: check_parsed_files(Checker*) (checker.cpp:4469)
==10369==    by 0x59E49E: main (main.cpp:2068)
==10369==  Address 0x1ffeff5318 is on thread 1's stack
==10369==  30536 bytes below stack pointer
```

**Comment by nakst** [comment]
This appears to have been fixed in the newest commit, but the Valgrind errors are still occurring. I will only a need issue.
