### ISSUE TITLE
LLVM API crash when `using` a global in debug mode.

### ISSUE THREAD

**Issue by AaronGlazer** [odin-lang/Odin#893]
## Context

With flags `-debug` and `-llvm-api`, running into a compiler crash when referencing a field of a global with `using`.

* Operating System: Windows
* Odin version: `odin version 0.13.1-f78b2a60`

## Expected Behavior

The program compiles successfully.

## Current Behavior

The compiler runs into an access violation error and crashes.

## Failure Information (for bugs)

From a quick debugging session it looks like it occurs in `LLVMDIBuilderInsertDeclareBefore` from `lb_add_debug_local_variable`.

### Steps to Reproduce

Minimum code to reproduce:

```odin
// sample.odin
package sample

My_Struct :: struct {
    a: int
}

the_struct: My_Struct;

main :: proc() {
    using the_struct;
    a += 1;
}
```

Build with `odin.exe build sample.odin -llvm-api -debug`. Note that it compiles successfully when not using both flags.

### Failure Logs

```
0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.
```

**Comment by wilsonk** [comment]
Still getting this error with the new backend (where -llvm-api is no longer needed). Just mentioning it here for posterity. Running under gdb gives this backtrace, if it helps:

```
#0  0x00000000029fbe60 in void llvm::invalidateParentIListOrdering<llvm::BasicBlock>(llvm::BasicBlock*) ()
#1  0x00000000029fbed0 in llvm::SymbolTableListTraits<llvm::Instruction>::addNodeToList(llvm::Instruction*) ()
#2  0x0000000002a8e00f in llvm::IRBuilderDefaultInserter::InsertHelper(llvm::Instruction*, llvm::Twine const&, llvm::BasicBlock*, llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, false>) const ()
#3  0x0000000002a37fce in llvm::DIBuilder::insertDeclare(llvm::Value*, llvm::DILocalVariable*, llvm::DIExpression*, llvm::DILocation const*, llvm::BasicBlock*, llvm::Instruction*) ()
#4  0x0000000002a381ff in llvm::DIBuilder::insertDeclare(llvm::Value*, llvm::DILocalVariable*, llvm::DIExpression*, llvm::DILocation const*, llvm::Instruction*) ()
#5  0x000000000061ad0d in lb_add_debug_local_variable (p=0x7fff08f7fdc0, ptr=0x5c08d40, 
    type=0x4c725c0 <basic_types+6480>, token=...) at src/llvm_backend.cpp:3080
#6  0x0000000000648988 in lb_get_using_variable (p=0x7fff08f7fdc0, e=0x7ffff6326270)
    at src/llvm_backend.cpp:11439
#7  0x0000000000648b5f in lb_build_addr_from_entity (p=0x7fff08f7fdc0, e=0x7ffff6326270, expr=0x7fffc8002010)
    at src/llvm_backend.cpp:11460
#8  0x00000000005f2b59 in lb_build_addr (p=0x7fff08f7fdc0, expr=0x7fffc8002010) at src/llvm_backend.cpp:11626
#9  0x0000000000624914 in lb_build_stmt (p=0x7fff08f7fdc0, node=0x7fffc80020f0) at src/llvm_backend.cpp:5060
#10 0x00000000006221de in lb_build_stmt_list (p=0x7fff08f7fdc0, stmts=...) at src/llvm_backend.cpp:3656
#11 0x0000000000622900 in lb_build_stmt (p=0x7fff08f7fdc0, node=0x7fffc8002180) at src/llvm_backend.cpp:4857
#12 0x0000000000656072 in lb_generate_code (gen=0x7fffffffcae8) at src/llvm_backend.cpp:14293
#13 0x000000000066b750 in main (arg_count=4, arg_ptr=0x7fffffffdf98) at src/main.cpp:2184
```
